In [44]:
from skimage import measure
import pandas as pd
from functions import niftiread, size3, getVoxelList
import numpy as np

folder = '/home/nirvan/Desktop/Projects/EcadMyo_08_all/EcadMyo_08_Tracking_Result/'
tim = 2
t2 = str(2)

Fullsize = niftiread(folder + t2 + '/Fullsize_' + t2 + '.nii')
Fullsize[Fullsize>0] = 1
Fullsize_2 = Fullsize.astype(bool)

Fullsize_2, orgnum = measure.label(Fullsize_2, connectivity=1, return_num=True)
stats1 = pd.DataFrame(measure.regionprops_table(Fullsize_2, properties=('label', 'centroid','coords')))
print(stats1.label)
VoxelList = stats1.coords
print(VoxelList)
print(type(VoxelList))
print(VoxelList[0][0][1])

print(VoxelList.shape[0])

# voxels = getVoxelList(Fullsize_2,orgnum)

# print(stats1)
# print(voxels)
print(np.size(VoxelList[0],axis=1))


0        1
1        2
2        3
3        4
4        5
      ... 
276    277
277    278
278    279
279    280
280    281
Name: label, Length: 281, dtype: int64
0      [[0, 133, 4], [0, 133, 5], [0, 134, 4], [0, 13...
1      [[0, 136, 6], [1, 136, 6], [1, 137, 6], [2, 13...
2      [[1, 75, 11], [1, 75, 12], [1, 76, 11], [1, 76...
3      [[2, 249, 9], [2, 249, 10], [3, 249, 9], [3, 2...
4      [[8, 44, 4], [9, 44, 4], [10, 44, 4], [11, 44,...
                             ...                        
276    [[498, 80, 7], [499, 79, 6], [499, 80, 6], [49...
277    [[501, 249, 3], [501, 249, 4], [501, 250, 3], ...
278    [[502, 271, 9], [502, 272, 9], [503, 270, 9], ...
279    [[505, 33, 6], [505, 34, 6], [505, 35, 6], [50...
280    [[507, 11, 4], [507, 11, 5], [508, 10, 4], [50...
Name: coords, Length: 281, dtype: object
<class 'pandas.core.series.Series'>
133
281
3


In [45]:
from skimage import measure
import pandas as pd
from functions import niftiread, size3, getVoxelList
import numpy as np

folder = '/home/nirvan/Desktop/Projects/EcadMyo_08_all/EcadMyo_08_Tracking_Result/'
tim = 2
t2 = str(2)
padding =[20,20,2]

Fullsize_1 = niftiread(folder + t2 + '/Fullsize_label_' + t2 + '.nii')
Fullsize_1_padding = np.pad(Fullsize_1, ((padding[0], padding[0]), (padding[1], padding[1]), (padding[2], padding[2])), 'constant')
[fx, fy, fz] = size3(Fullsize_1_padding)

Fullsize_1[Fullsize_1>0] = 1
Fullsize_1 = Fullsize_1.astype(bool)

Fullsize_2, orgnum = measure.label(Fullsize_2, connectivity=1, return_num=True)
stats1 = pd.DataFrame(measure.regionprops_table(Fullsize_2, properties=('label', 'centroid','coords')))
print(stats1.label)
VoxelList = stats1.coords
print(VoxelList)
print(type(VoxelList))
print(VoxelList[0][0][1])

print(VoxelList.shape[0])

# voxels = getVoxelList(Fullsize_2,orgnum)

# print(stats1)
# print(voxels)
print(np.size(VoxelList[0],axis=1))

0        1
1        2
2        3
3        4
4        5
      ... 
276    277
277    278
278    279
279    280
280    281
Name: label, Length: 281, dtype: int64
0      [[0, 133, 4], [0, 133, 5], [0, 134, 4], [0, 13...
1      [[0, 136, 6], [1, 136, 6], [1, 137, 6], [2, 13...
2      [[1, 75, 11], [1, 75, 12], [1, 76, 11], [1, 76...
3      [[2, 249, 9], [2, 249, 10], [3, 249, 9], [3, 2...
4      [[8, 44, 4], [9, 44, 4], [10, 44, 4], [11, 44,...
                             ...                        
276    [[498, 80, 7], [499, 79, 6], [499, 80, 6], [49...
277    [[501, 249, 3], [501, 249, 4], [501, 250, 3], ...
278    [[502, 271, 9], [502, 272, 9], [503, 270, 9], ...
279    [[505, 33, 6], [505, 34, 6], [505, 35, 6], [50...
280    [[507, 11, 4], [507, 11, 5], [508, 10, 4], [50...
Name: coords, Length: 281, dtype: object
<class 'pandas.core.series.Series'>
133
281
3


In [52]:
print(VoxelList.shape[0])
np.size(VoxelList,axis=0)


281


281

In [48]:
np.size(VoxelList[0], axis=0)

10

In [54]:
stats1.shape[0]

281

In [59]:
stats2 = stats1.sort_values(by=['coords'], ascending=False, ignore_index = False)


ValueError: operands could not be broadcast together with shapes (5,3) (22,3) 

In [87]:
count = np.zeros(stats1.shape[0])
for i in range(stats1.shape[0]):
    count[i] = np.size(stats1.coords[i],axis=0)
stats1['Count']=count.astype(int)


In [88]:
stats1

label  centroid-0  centroid-1  centroid-2  \
0        1    0.800000  133.500000    4.600000   
1        2    1.833333  136.666667    6.000000   
2        3    1.333333   75.500000   11.666667   
3        4    3.538462  251.307692    9.461538   
4        5    9.800000   44.200000    4.000000   
..     ...         ...         ...         ...   
276    277  499.900000   79.800000    6.400000   
277    278  502.266667  250.800000    2.933333   
278    279  502.800000  270.800000    9.000000   
279    280  505.625000   34.000000    6.125000   
280    281  509.363636   10.000000    4.590909   

                                                coords  Count  
0    [[0, 133, 4], [0, 133, 5], [0, 134, 4], [0, 13...     10  
1    [[0, 136, 6], [1, 136, 6], [1, 137, 6], [2, 13...      6  
2    [[1, 75, 11], [1, 75, 12], [1, 76, 11], [1, 76...      6  
3    [[2, 249, 9], [2, 249, 10], [3, 249, 9], [3, 2...     13  
4    [[8, 44, 4], [9, 44, 4], [10, 44, 4], [11, 44,...      5  
..                                                 ...    ...  
276  [[498, 80, 7], [499, 79, 6], [499, 80, 6], [49...     10  
277  [[501, 249, 3], [501, 249, 4], [501, 250, 3], ...     15  
278  [[502, 271, 9], [502, 272, 9], [503, 270, 9], ...      5  
279  [[505, 33, 6], [505, 34, 6], [505, 35, 6], [50...      8  
280  [[507, 11, 4], [507, 11, 5], [508, 10, 4], [50...     22  

[281 rows x 6 columns]

In [92]:
ct = []
for i in range(stats1.shape[0]):
    ct.append(np.size(stats1.coords[i],axis=0))
stats1['Ct']=ct


In [93]:
stats1

label  centroid-0  centroid-1  centroid-2  \
0        1    0.800000  133.500000    4.600000   
1        2    1.833333  136.666667    6.000000   
2        3    1.333333   75.500000   11.666667   
3        4    3.538462  251.307692    9.461538   
4        5    9.800000   44.200000    4.000000   
..     ...         ...         ...         ...   
276    277  499.900000   79.800000    6.400000   
277    278  502.266667  250.800000    2.933333   
278    279  502.800000  270.800000    9.000000   
279    280  505.625000   34.000000    6.125000   
280    281  509.363636   10.000000    4.590909   

                                                coords  Count  Ct  
0    [[0, 133, 4], [0, 133, 5], [0, 134, 4], [0, 13...     10  10  
1    [[0, 136, 6], [1, 136, 6], [1, 137, 6], [2, 13...      6   6  
2    [[1, 75, 11], [1, 75, 12], [1, 76, 11], [1, 76...      6   6  
3    [[2, 249, 9], [2, 249, 10], [3, 249, 9], [3, 2...     13  13  
4    [[8, 44, 4], [9, 44, 4], [10, 44, 4], [11, 44,...      5   5  
..                                                 ...    ...  ..  
276  [[498, 80, 7], [499, 79, 6], [499, 80, 6], [49...     10  10  
277  [[501, 249, 3], [501, 249, 4], [501, 250, 3], ...     15  15  
278  [[502, 271, 9], [502, 272, 9], [503, 270, 9], ...      5   5  
279  [[505, 33, 6], [505, 34, 6], [505, 35, 6], [50...      8   8  
280  [[507, 11, 4], [507, 11, 5], [508, 10, 4], [50...     22  22  

[281 rows x 7 columns]

In [101]:

print(type(stats1.coords[0]))
stats1.coords[0]


<class 'numpy.ndarray'>


array([[  0, 133,   4],
       [  0, 133,   5],
       [  0, 134,   4],
       [  0, 134,   5],
       [  1, 133,   4],
       [  1, 133,   5],
       [  1, 134,   4],
       [  1, 134,   5],
       [  2, 133,   5],
       [  2, 134,   5]])

In [124]:
b = stats2.coords[1]
print(b)
threeDimg1 = niftiread('/home/nirvan/Desktop/Projects/EcadMyo_08_all/3DImage/' + 'EcadMyo_08/' + 'Ecad/' + 'threeDimg_' +
                                   '00' + str(2) + '.nii')
threeDimgPixellist1 = []

for i1 in range(np.size(b,axis=0)):
    threeDimgPixellist1.append(threeDimg1[b[i1,1],b[i1,0],b[i1,2]])
print(threeDimgPixellist1)
print(np.amax(threeDimg1))
threeDimgPixellist1 = sorted(threeDimgPixellist1,reverse=True)
print(threeDimgPixellist1)
print(sum(threeDimgPixellist1))
print(np.size(threeDimgPixellist1))

[[  0 136   6]
 [  1 136   6]
 [  1 137   6]
 [  2 137   6]
 [  3 137   6]
 [  4 137   6]]
[97.0, 177.0, 160.0, 173.0, 81.0, 1056.0]
23259.0
[1056.0, 177.0, 173.0, 160.0, 97.0, 81.0]
1744.0
6


In [94]:
stats2 = stats1.sort_values(by='Count', axis=0, ascending=False, ignore_index=False)

In [95]:
stats2

label  centroid-0  centroid-1  centroid-2  \
81      82  175.614035  238.649123    5.122807   
199    200  359.104167  261.687500    4.041667   
53      54  104.840909  203.431818    6.136364   
183    184  324.439024   79.024390    2.731707   
221    222  404.342857  238.714286   12.114286   
..     ...         ...         ...         ...   
154    155  272.200000   58.000000    7.400000   
254    255  456.400000  109.000000    4.400000   
109    110  214.600000   54.800000    1.600000   
141    142  262.000000  219.200000   11.400000   
140    141  259.800000  159.000000    9.400000   

                                                coords  Count  Ct  
81   [[170, 242, 5], [171, 241, 4], [171, 241, 5], ...     57  57  
199  [[356, 259, 5], [357, 259, 4], [357, 259, 5], ...     48  48  
53   [[102, 202, 6], [102, 202, 7], [102, 203, 6], ...     44  44  
183  [[322, 77, 1], [322, 77, 2], [322, 77, 3], [32...     41  41  
221  [[402, 238, 12], [402, 238, 13], [402, 239, 12...     35  35  
..                                                 ...    ...  ..  
154  [[271, 58, 7], [272, 58, 7], [272, 58, 8], [27...      5   5  
254  [[455, 109, 5], [456, 109, 4], [456, 109, 5], ...      5   5  
109  [[214, 54, 1], [214, 55, 1], [214, 55, 2], [21...      5   5  
141  [[261, 219, 11], [262, 219, 11], [262, 219, 12...      5   5  
140  [[259, 159, 9], [259, 159, 10], [260, 159, 9],...      5   5  

[281 rows x 7 columns]

In [135]:
import statistics
a=[1,1,1,2,2,2,2,3,3,3,4]
value = statistics.mode(np.array(a).flatten())
u, c = np.unique(np.array(a), return_counts=True)
Value_f = dict(zip(u, c))[value]

In [136]:
Value_f

4

In [137]:
value

2

In [148]:
import numpy as np
def intersect_mtlb(a, b):
    a1, ia = np.unique(a, return_index=True)
    b1, ib = np.unique(b, return_index=True)
    aux = np.concatenate((a1, b1))
    print(aux)
    aux.sort()
    print(aux)
    c = aux[:-1][aux[1:] == aux[:-1]]
    print(c)
    print(a1, ia)
    print(b1,ib)
    return c, ia[np.isin(a1, c)], ib[np.isin(b1, c)]


# a = np.array([7, 1, 7, 7, 4]);
# b = np.array([7, 0, 4, 4, 0]);
a = np.array([1,2,3,4,5])
b = np.array([6,6,7,8,9])
c, ia, ib = intersect_mtlb(a, b)
print(c, ia, ib)
print(type(c))
print(np.size(c,axis=0))

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[]
[1 2 3 4 5] [0 1 2 3 4]
[6 7 8 9] [0 2 3 4]
[] [] []
<class 'numpy.ndarray'>
0


In [151]:
xx = []
for i in range(10):
    xx.append([i,i+1])

In [152]:
xx

[[0, 1],
 [1, 2],
 [2, 3],
 [3, 4],
 [4, 5],
 [5, 6],
 [6, 7],
 [7, 8],
 [8, 9],
 [9, 10]]

In [169]:
import numpy as np
def setdiff(a, b):
    a1, ia = np.unique(a, return_index=True)
    b1, ib = np.unique(b, return_index=True)
    return np.asarray([i for i in a1 if i not in b1])


# a = np.array([7, 1, 7, 7, 4]);
# b = np.array([7, 0, 4, 4, 0]);
a = np.array([5,2,3,4,1,4,5,5,6,6])
b = np.array([5,4,7,8,9])
print(setdiff(a,b))

# c, ia, ib = setdiff(a, b)
# print(c, ia, ib)
# print(type(c))
# print(np.size(c,axis=0))

[1 2 3 6]


In [159]:
xxxx = [1,2,3,4]
print(xxxx[1:-1])

[2, 3]


In [175]:
def isempty(a):
    return True if np.size(a, axis=0) == 0 else False
print(isempty([]))

isempty([1,2,3])

True


False

In [178]:
np.random.rand()

0.3539297128281379