In [42]:
import PIL.Image
from PIL import Image
import glob
import numpy as np
import nibabel as nib
from nilearn.image import resample_img

addr2 = 'C:/Users/Gautam/Desktop/oneone/3DImage/EcadMyo_08/Ecad/'
Files = glob.glob(addr2 + '*.nii')
print(Files[1])

V = np.asarray(nib.load(Files[1]).dataobj).astype(np.float32).squeeze()
print(np.shape(V))
print(V)
V = 1-V
print(V)
type(V)
I3d = [35, 35, 15]
V2 = np.uint8(V)
# V3 = resize(V2,I3d,order=1)
# print(np.shape(V3))
# V = Image.open('C:/Users/Gautam/Desktop/oneone/3DImage/EcadMyo_08/Ecad/threeD_img0002.nii')

# print(np.shape(V))
# newsize = (35,35,15)
# V_resized = V2.resize((35,35,15),Image.LINEAR)
#
# print(np.shape(V_resized))
upsampled_nii = resample_img(V, target_affine=np.eye(3)*0.5, interpolation='nearest')





C:/Users/Gautam/Desktop/oneone/3DImage/EcadMyo_08/Ecad\threeD_img0002.nii
(512, 280, 15)
[[[-32687. -32673. -32677. ... -32689. -32683. -32693.]
  [-30753. -31096. -31970. ... -32695. -32675. -32677.]
  [-31697. -30622. -31267. ... -32680. -32666. -32677.]
  ...
  [-32667. -32675. -31861. ... -32661. -32687. -32684.]
  [-32668. -31361. -31583. ... -31932. -32677. -32682.]
  [-32660. -32682. -32686. ... -32461. -31267. -32518.]]

 [[-32051. -32441. -32539. ... -32682. -32689. -32685.]
  [-31398. -31825. -32375. ... -32686. -32678. -32689.]
  [-31749. -31189. -31725. ... -32684. -32675. -32688.]
  ...
  [-32684. -32683. -31863. ... -32090. -32690. -32686.]
  [-32320. -31980. -32214. ... -32365. -32678. -32688.]
  [-32452. -32594. -32657. ... -32505. -31670. -32566.]]

 [[-30514. -31507. -31728. ... -32596. -32119. -32558.]
  [-30674. -31909. -32675. ... -32481. -31367. -32542.]
  [-31363. -31673. -32257. ... -32685. -32685. -32692.]
  ...
  [-32690. -32687. -32189. ... -32069. -32684. -3

array([512, 280,  15])